### ISSUE TITLE
[Bug] ArgumentNullException when navigating before to a page with CameraView before another page is disposed 

### ISSUE THREAD

**Issue by thomasgalliker** [thomasgalliker/CameraScanner.Maui#39]
#### Steps to Reproduce

1. Navigate to a page containing CameraView.
2. Go back.
3. Navigate very quickly back to the previously opened page which contains an instance of CameraView.

#### Expected Behavior
- Wait until everything is disposed and re-initialize CameraView again.

#### Actual Behavior
- App crashes.

#### Basic Information
- Version with issue: 1.4.25-pre
- Last known good version: N/A

#### Screenshots, Attachments, Links
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[NSNumber,Single](IEnumerable`1 source, Func`2 selector)
   at CameraScanner.Maui.CameraManager.UpdateDeviceSwitchZoomFactors()
   at CameraScanner.Maui.CameraManager.StartAsync()
   at CameraScanner.Maui.CameraManager.UpdateCameraEnabled()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at PatientApp.Program.Main(String[] args) in /Users/thomasgalliker/src/gitlab/benecura-ng-2/PatientApp/Platforms/iOS/Program.cs:line 13
```

**Comment by thomasgalliker** [comment]
This is definitly a race condition. Strangly I cannot reproduce it with the sample app in this repo. Are you using Prism to navigate between pages?
