### ISSUE TITLE
[Bug] UI Freeze and 'Cannot Access a Disposed Object' Error While Continuously Scanning Barcodes or Repeatedly Scanning a Single Barcode

### ISSUE THREAD

**Issue by HaileyKim04** [thomasgalliker/CameraScanner.Maui#40]
#### Description

 
This issue arises when scanning a single barcode for an extended period, when the camera stops functioning after multiple scans, or when switching between barcode scanning and unrelated screens (e.g., a barcode image or any random background)**

#### Steps to Reproduce

1. Navigate to a page containing `CameraView`.
2. Scan a barcode.
3. Switch back and forth between barcode scanning and unrelated screens multiple times.
4. The issue manifests as the camera freezing or stopping after several repeated cycles.

#### Expected Behavior
- The camera should continue functioning without freezing or stopping, regardless of the duration of scanning or repeated interactions with unrelated pages/screens.

#### Actual Behavior
- The camera stops working or freezes.
- Error thrown: `Cannot access a disposed object. Object name: 'AndroidX.Camera.View.Transform.CoordinateTransform'.`

#### Basic Information
- Version with issue: 1.4.19
- Last known good version: 

#### Screenshots, Attachments, Links

`Cannot access a disposed object. Object name: 'AndroidX.Camera.View.Transform.CoordinateTransform'.`

**Comment by HaileyKim04** [comment]
Hello @thomasgalliker , In the context of BarcodeAnalyze under Android codebase, the current implementation catches exceptions and log it 

catch (Exception ex)
{
    this.logger.LogError(ex, "Analyze failed with exception");
}

I’m wondering if this supposed to be throwing the exception

**Comment by thomasgalliker** [comment]
Thanks for reporting this issue. I have to look at it.
Regarding the catched exception: the code snipped bit out of context. In some situations it‘s totally fine to catch and not rethrow the exception.

**Comment by thomasgalliker** [comment]
@HaileyKim04 are you using AppShell or classic navigation? If you find the time to create a small repro app which causes this issue, I‘d be very happy.

**Comment by HaileyKim04** [comment]
Yes, I am using classic navigation. This is the repository, and I noticed that scanning stops after scanning certain barcodes in the repository.

[MauiApp1.zip](https://github.com/user-attachments/files/18350627/MauiApp1.zip)

**Comment by Magnuskeel** [comment]
Hi , just want to say amazing barcode scanning control, unfortunately I am having the same issue: 

CameraScanner.Maui.BarcodeAnalyzer: Error: Analyze failed with exception

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AndroidX.Camera.View.Transform.CoordinateTransform'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 39
   at AndroidX.Camera.View.Transform.CoordinateTransform.MapRect(RectF rect) in D:\a\_work\1\s\generated\androidx.camera.camera-view\obj\Release
et8.0-android\generated\src\AndroidX.Camera.View.Transform.CoordinateTransform.cs:line 112
   at CameraScanner.Maui.Platforms.Services.BarcodeScanner.ProcessBarcodeResult(Object inputResults, HashSet`1 outputResults, CoordinateTransform transform) in C:\Users\mkoso\source\repos\CameraScanner.Maui\Platforms\Android\Services\BarcodeScanner.cs:line 111
   at CameraScanner.Maui.CameraManager.PerformBarcodeDetectionAsync(IImageProxy proxy) in C:\Users\mkoso\source\repos\CameraScanner.Maui\Platforms\Android\CameraManager.cs:line 404
   at CameraScanner.Maui.Utils.SyncHelper.RunOnceAsync(Func`1 task) in C:\Users\mkoso\source\repos\CameraScanner.Maui\Utils\SyncHelper.cs:line 19
   at CameraScanner.Maui.BarcodeAnalyzer.Analyze(IImageProxy proxyImage) in C:\Users\mkoso\source\repos\CameraScanner.Maui\Platforms\Android\BarcodeAnalyzer.cs:line 62
[0:] CameraScanner.Maui.BarcodeAnalyzer: Error: Analyze -> IImageProxy.Close failed with exception

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AndroidX.Camera.Core.SettableImageProxy'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 57
   at AndroidX.Camera.Core.ForwardingImageProxy.Close()
   at CameraScanner.Maui.BarcodeAnalyzer.Analyze(IImageProxy proxyImage) in C:\Users\mkoso\source\repos\CameraScanner.Maui\Platforms\Android\BarcodeAnalyzer.cs:line 88


I am using AppShell navigation

**Comment by thomasgalliker** [comment]
Thanks for reporting 👍🏻 I'm currently bit in pre-release stress but I'm positive we can solve this.

**Comment by Magnuskeel** [comment]
Not sure yet but might have found a fix,  when i am confident its actually working consistently I can show you what I did. Prolly a threading issue.

**Comment by Magnuskeel** [comment]
I think because the Analyze method was set to async void along with this line 

`var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));`

you were getting a race condition.

if you remove the async from the method signature and wrap that above line of code a Task.Run like this:

```
Task.Run(async () =>
{
    var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));

    if (run == false)
    {
        // this.logger.LogDebug("Analyze -> frame skipped (already in progress)");
    }
}).Wait();   
```

The problem seems to stop happening. 

so the entire method looks like this.

    ```
public void Analyze(IImageProxy proxyImage)
    {

        try
        {                   

            if (this.PauseScanning)
            {
                return;
            }

            if (this.BarcodeDetectionFrameRate is not uint r || r is 0u or 1u || this.skippedFrames == null || ++this.skippedFrames >= r)
            {
                // this.logger.LogDebug("Analyze");

                if (this.cameraManager.CaptureNextFrame)
                {
                    this.cameraManager.CaptureImage(proxyImage);
                }
                else
                {
                    Task.Run(async () =>
                    {
                        var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));

                        if (run == false)
                        {
                            // this.logger.LogDebug("Analyze -> frame skipped (already in progress)");
                        }
                    }).Wait();                        
                }

                if (this.BarcodeDetectionFrameRate != null)
                {
                    this.skippedFrames = 0;
                }
            }
            else
            {
                // this.logger.LogDebug("Analyze -> frame skipped (BarcodeDetectionFrameRate)");
            }
        }
        catch (Exception ex)
        {
            this.logger.LogError(ex, "Analyze failed with exception");
        }
        finally
        {
            try
            {
                if(proxyImage != null)
                    proxyImage.Close();
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, "Analyze -> IImageProxy.Close failed with exception");
                 MainThread.BeginInvokeOnMainThread(() => this.cameraManager.StartAsync());
            }                
        }            
    }
}
```

And there doesnt seem to be a performance hit. Do with it what you will :)

**Comment by haeun159951** [comment]
> Is it possible to reproduce with the sample app in this repository? Or can anyone create a super-small sample app which causes this issue?

Yes, I could reproduce this error in the sample demo app.


One strange thing is I cannot reproduce the issue in sample as long as the library Project is referenced in the Sample project. 
If I remove the library project reference and add the Nuget version, no matter which version, try the latest, pre-release, and 1.3 as well, I can reproduce the issue in the sample project.

I used the QR code scanner page and ViewModel to edit the code and using the barcode on the screen, I kept scrolling the bar quickly so I could reproduce it. It took around 3 minutes to [do.]. I could see some exceptiothe ns on console in Rider.

![Image](https://github.com/user-attachments/assets/20990cc0-2257-4d00-88d0-6bccd9c52d48)

```
**QrCodeScannerPage.xaml** 
 
<c:CameraView
            Grid.Row="0"
            CameraEnabled="{Binding IsScannerEnabled}"
            OnDetectionFinishedCommand="{Binding OnDetectionFinishedCommand}"/>

        <Label BackgroundColor="White" 
               TextColor="Black"
               WidthRequest="200" Height="80" Text="{Binding ScannedText}"/>

**QrCodeScannerViewModel.cs**
 
   private async Task HandleScanResultAsync(BarcodeResult[] barcodeResults)
        {
            try
            {
                if (barcodeResults.FirstOrDefault() is BarcodeResult barcodeResult)
                {
                    // this.IsScannerPause = true;
                    //
                    // var stop = await this.dialogService.DisplayAlertAsync(
                    //     "Barcode found",
                    //     $"BarcodeType=\"{barcodeResult.BarcodeType}\"{Environment.NewLine}" +
                    //     $"BarcodeFormat=\"{barcodeResult.BarcodeFormat}\"{Environment.NewLine}" +
                    //     $"DisplayValue=\"{barcodeResult.DisplayValue}\"",
                    //     "Stop", "Continue");
                    //
                    // if (stop)
                    // {
                    //     this.StopCamera();
                    // }
                    // else
                    // {
                    //     this.IsScannerPause = false;
                    // }

                    this.ScannedText = barcodeResult.DisplayValue;
                }
            }
```

**Comment by haeun159951** [comment]
> I think because the Analyze method was set to async void along with this line
> 
> `var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));`
> 
> you were getting a race condition.
> 
> if you remove the async from the method signature and wrap that above line of code a Task.Run like this:
> 
> ```
> Task.Run(async () =>
> {
>     var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));
> 
>     if (run == false)
>     {
>         // this.logger.LogDebug("Analyze -> frame skipped (already in progress)");
>     }
> }).Wait();   
> ```
> 
> The problem seems to stop happening.
> 
> so the entire method looks like this.
> 
> ```
> ```
> ```
> 
> public void Analyze(IImageProxy proxyImage) {
> 
> ```
>     try
>     {                   
> 
>         if (this.PauseScanning)
>         {
>             return;
>         }
> 
>         if (this.BarcodeDetectionFrameRate is not uint r || r is 0u or 1u || this.skippedFrames == null || ++this.skippedFrames >= r)
>         {
>             // this.logger.LogDebug("Analyze");
> 
>             if (this.cameraManager.CaptureNextFrame)
>             {
>                 this.cameraManager.CaptureImage(proxyImage);
>             }
>             else
>             {
>                 Task.Run(async () =>
>                 {
>                     var run = await this.syncHelper.RunOnceAsync(() => this.cameraManager.PerformBarcodeDetectionAsync(proxyImage));
> 
>                     if (run == false)
>                     {
>                         // this.logger.LogDebug("Analyze -> frame skipped (already in progress)");
>                     }
>                 }).Wait();                        
>             }
> 
>             if (this.BarcodeDetectionFrameRate != null)
>             {
>                 this.skippedFrames = 0;
>             }
>         }
>         else
>         {
>             // this.logger.LogDebug("Analyze -> frame skipped (BarcodeDetectionFrameRate)");
>         }
>     }
>     catch (Exception ex)
>     {
>         this.logger.LogError(ex, "Analyze failed with exception");
>     }
>     finally
>     {
>         try
>         {
>             if(proxyImage != null)
>                 proxyImage.Close();
>         }
>         catch (Exception ex)
>         {
>             this.logger.LogError(ex, "Analyze -> IImageProxy.Close failed with exception");
>              MainThread.BeginInvokeOnMainThread(() => this.cameraManager.StartAsync());
>         }                
>     }            
> }
> ```
> 
> }
> 
> ```
> 
> And there doesnt seem to be a performance hit. Do with it what you will :)
> ```

I usually get these three exceptions, but after applying this code, the last two are hard to reproduce. However, I still get the PreviewView exception. No UI freezing issue so far.

Exceptions:

Cannot access a disposed object. Object name: 'AndroidX.Camera.View.PreviewView'.
Cannot access a disposed object. Object name: 'AndroidX.Camera.Core.SettableImageProxy'.
Cannot access a disposed object. Object name: 'AndroidX.Camera.View.Transform.CoordinateTransform'.

**Comment by haeun159951** [comment]
> Ok. I gonna have a look at this code. On which devices did you have the UI freezes?

I’ve tried two different devices: a Samsung S21 and an A15. Sometimes, I can reproduce the UI freeze, but not always. Also, the scanning stopped working, and I got the exception: 'Cannot access a disposed object. Object name: 'AndroidX.Camera.Core.SettableImageProxy'

**Comment by decv86** [comment]
Despite the bugs, this is the best plugin at the moment. Thanks for your work!

**Comment by thomasgalliker** [comment]
We‘re using this plugin in production apps. And yes we also experience the ObjectDisposedException. Sadly there are even worse problems I have to care about. I‘ll come back to this.

**Comment by srpai746** [comment]
@thomasgalliker  Any update on this issue?
Can we expect a new version of this nuget package with the fix as in
https://github.com/thomasgalliker/CameraScanner.Maui/issues/40#issuecomment-2654624947 soon?

**Comment by thomasgalliker** [comment]
I'm looking into it right now @srpai746. Thanks for the proposed solution @haeun159951. I don't understand why Task.Run(...).Wait() should solve the problem. It just runs the PerformBarcodeDetectionAsync method in another task. Strangly I cannot reproduce the problem until now. I'm trying with different devices. Does anyone have a hint on how I can reproduce this issue?

**Comment by haeun159951** [comment]
> I'm looking into it right now [@srpai746](https://github.com/srpai746). Thanks for the proposed solution [@haeun159951](https://github.com/haeun159951). I don't understand why Task.Run(...).Wait() should solve the problem. It just runs the PerformBarcodeDetectionAsync method in another task. Strangly I cannot reproduce the problem until now. I'm trying with different devices. Does anyone have a hint on how I can reproduce this issue?

Have you tried this way?

remove the library project reference and add the Nuget version, no matter which version, try the latest, pre-release, and 1.3 as well, I can reproduce the issue in the sample project.

**Comment by thomasgalliker** [comment]
Ok, I'll try with the nuget. Good catch.
But I think I found the cause of the disposed CoordinateTransform. I guess CoordinateTransform (in method PerformBarcodeDetectionAsync) is disposed too early.

**Comment by thomasgalliker** [comment]
@haeun159951 can you also reproduce this issue when you install the latest pre-release nuget (version 1.4.32-pre as of now)?

**Comment by haeun159951** [comment]
> [@haeun159951](https://github.com/haeun159951) can you also reproduce this issue when you install the latest pre-release nuget (version 1.4.32-pre as of now)?

yes

**Comment by thomasgalliker** [comment]
Can you update your solution with CameraScanner.Maui version 1.4.33-pre and try again?
I removed the direct reference in the sample app of this repository and installed the nuget and it still doesn't happen on my devices. I tested with an Samsung A7, Google Pixel 5 and HUAWEI WAS-LX1. The CoordinateTransform problem does never happen. Very strange.

**Comment by haeun159951** [comment]
> Can you update your solution with CameraScanner.Maui version **1.4.33-pre** and try again? I removed the direct reference in the sample app of this repository and installed the nuget and it still doesn't happen on my devices. I tested with an Samsung A7, Google Pixel 5 and HUAWEI WAS-LX1. The CoordinateTransform problem does never happen. Very strange.

May I ask how have you tested? for me, i tested a barcode on barcode generator website and using fast scrolling for 2 mins to reproduce errors

**Comment by thomasgalliker** [comment]
I tested with the UniversalScannerPage in the CameraDemoApp. I used (mostly) EAN13 barcodes and QR codes, printed out on paper and I leave the barcodes without movement in front of the mobile phones. I think it's shouldn't make any difference if I scan the barcodes from the display or from paper - nor should it not make a difference whether the barcode is moving.

**Comment by thomasgalliker** [comment]
Did you try version 1.4.33-pre, @haeun159951?

**Comment by haeun159951** [comment]
> Did you try version 1.4.33-pre, [@haeun159951](https://github.com/haeun159951)?

Do you mean try with Task.run method (solution) + using 1.4.33?

**Comment by thomasgalliker** [comment]
I guess you installed the nuget CameraScanner.Maui? I published two new versions yesterday, 1.4.32-pre und 1.4.33-pre. I wonder if the problem still persists with the latest pre-release.

**Comment by thomasgalliker** [comment]
If anyone could try nuget version 1.4.33-pre and give feedback if the original issue (by @HaileyKim04) is solved, would be highly appreciated.

**Comment by thomasgalliker** [comment]
@haeun159951 this looks like another problem. Do you experience the same exception with 1.4.29-pre too?

**Comment by haeun159951** [comment]
> [@haeun159951](https://github.com/haeun159951) this looks like another problem. Do you experience the same exception with 1.4.29-pre too?

still getting this error and UI freezing and it doesn't scan anymore

**Comment by thomasgalliker** [comment]
I tested the following:
- I took the CameraDemoApp in this repository and remove the direct project reference to CameraScanner.Maui.csproj. Instead, I installed the nuget package CameraScanner.Maui version 1.4.29-pre
- Then I used your code changes (QRCodeScannerViewModel+Page) and started a continous scan on my Android Google Pixel 5 device.
- After 1min, the UI freezes (to be precise: Not the UI freezes, but the scanner does not continue to return barcode results).
- When I update the nuget CameraScanner.Maui from 1.4.29-pre to 1.4.33-pre, the same problem does not happen again.

Can you confirm - or disagree?

**Comment by thomasgalliker** [comment]
We rolled this fix to production and no longer see the problem in our crash reporting tool. Let me know if it works for you too.
